name: Notify when a pull request in made to master branch
on:  
  pull_request:
    branches:
      - prueba1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Notify when someone creates a pull request on mentioned branches
        id: notify-on-pr
        uses: ./
        with:
          mobile_no: ${{ secrets.MOBILE_NO }}
      - name: Run
        run: echo 'Sending you notification'