name: Notify when a pull request in made to master branch
on:  
  pull_request:
    branches:
      - prueba1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: echo 'Sending you notification'